---
:login: skynet
:mdp: "***"
:creation:
  # la création demande une validation du mail avant de pouvoir faire quoi que ce sois. Donc la création auto est vraiment utile ?
  :create: 'true' # indique si le compte doit être crée dans le cas ou il n'existe pas
  :mail: lala@la.la # mail utilisé pour le formulaire de création
  :description: "une description" # nom donnée a la nouvelle ecurie
  :message_forum:
    :titre: 'teston' # titre du message
    :message: 'test 1 2 1 2' # message posté sur le forum lors de la création
:equipement:
#contrainte d'achat des équipements
:tournoi:
#choix des équipes
#paramètre de tactique de groupe ?
:amélioration:
  :ordre: # ordre dans le quels des amélio sont monté
    :tactique: 2
    :combattant: 1
    :équipement: 3
  :stockage:
  # par default surement acheté un emplacement si un glad veux acheté un équipement mais que le coffre est plein
  # inutile d'acheté sinon
  :hebergement:
  # definir les facteurs de décision pour l'achat d'un hébergement
  # rien acheté d'autre ?
  # acheté un hébergement après x credit dépensé en équipement ?
  # acheté dès qu'on a les sous ? (risque de jamais les avoirs pour les derniers niveaux)
:create_glad: 'true' # indique si le bot doit crée les glad ou pas
:glad:
# les glad sont crée dès que possible.
# il peut y avoir un infinité de glad de paramétré mais une écurie ne peut avoir que 11 glad en même temps max (10 hébèrgement + 1 clan). Ca peut servir pour un évenement ou Mohja change manuellement cette limite pour cette écurie au lieu de devoir crée 36 fois la même.
# si le premier glad meurs, il est recrée a l'identique
# comme les noms sont unique, il existe plusieurs variable pour que le noms sois valide
#   %n represente le numero du gladiateur. il commence a 1 puis est incrementé a chaque morts
#   %p represente la position du gladiateur. si c'est le premier de la liste c'est 1, si c'est le troisieme c'est 3, etc...
#   %x represente une valeur quelconque. le bot tente le 1 puis le 2, etc... jusqu'a que la création passe
#   %r idem que x mais en random entre 0 et combien ? 1 000 ? 10 000 ? plus ?
#   le %n et %p permette de facilement repéré a quel entré du tableau ils correspondents et suffise pour des noms unique a l'écurie
#   le %x et %r permette d'être sur que le nom passe, notament si les nom sont utilisé par plusieurs écurie
#   si le nom ne passe pas, le glad n'est pas crée !!
#   si le modele est 'toto' le bot cherchera le fichier de config 'toto.yaml' dans le repertoire 'gladiateur'
- :nom: pretre_%x # pretre_1
  :modele: soigneur
- :nom: druide_%x # druide_1
  :modele: soigneur2
- :nom: bourrin_%p_%x # bourrin_1_1
  :modele: attaquant
- :nom: bourrin_%p_%x # bourrin_2_1
  :modele: attaquant
- :nom: bourrin_%p_%x # bourrin_3_1
  :modele: attaquant
